
{{- if .Values.managedCertificate.enabled }}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: {{ .Values.managedCertificate.name }}
spec:
  domains:
    - {{ .Values.managedCertificate.domain }}
{{- end }}
